### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by IanLeung12** [TheChoco1/VBC-Calculator#1]
Do I have to take the save file from the run or does it run automatically when i run the sim

**Comment by TheChoco1** [comment]
> Do I have to take the save file from the run or does it run automatically when i run the sim

So essentially this is an outdated calculator with numbers from last year. You input numbers in the main.js file and it console.log's the results. 

You would have to download the files and run them in a terminal or in an editor. I don't recommend using it as again, the numbers are from last year and it wouldn't help you that much besides maybe the staff calculator and the estimated attendance.

**Comment by IanLeung12** [comment]
oh i see, how did you find the numbers to use

**Comment by TheChoco1** [comment]
Mostly through trial and error, some were given by the simulator.

**Comment by IanLeung12** [comment]
Thanks!
